import { useLocalSearchParams, router } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { editMessage, getMessages, markConversationRead, recallMessage, sendMessage } from "../../lib/messages";
import { supabase } from "../../lib/supabase";

export default function ChatScreen(){
  const {id}=useLocalSearchParams<{id:string}>();
  const [messages,setMessages]=useState<any[]>([]); const [text,setText]=useState(""); const [sending,setSending]=useState(false); const [myId,setMyId]=useState<string|null>(null);
  async function load(){if(!id)return; const {data:{user}}=await supabase.auth.getUser();setMyId(user?.id??null);setMessages(await getMessages(id));await markConversationRead(id);}
  useEffect(()=>{if(!id)return;load().catch(e=>Alert.alert("Chat unavailable",e.message));const channel=supabase.channel(`chat:${id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${id}`},payload=>setMessages(current=>current.some(x=>x.id===payload.new.id)?current:[...current,payload.new])).subscribe();return()=>{supabase.removeChannel(channel);};},[id]);
  async function send(){if(!id||!text.trim())return;try{setSending(true);const sent=await sendMessage(id,text);setMessages(x=>x.some(m=>m.id===sent.id)?x:[...x,sent]);setText("");}catch(e){Alert.alert("Message not sent",e instanceof Error?e.message:"Try again.");}finally{setSending(false);}}
  async function actions(m:any){if(m.sender_id!==myId||m.recalled_at)return;const age=Date.now()-new Date(m.created_at).getTime();if(age>120000)return Alert.alert("Edit window ended","Messages can only be edited or recalled for two minutes.");Alert.alert("Message options","Choose an action",[{text:"Edit",onPress:()=>Alert.prompt?.("Edit message",undefined,async value=>{if(value){await editMessage(m.id,value);await load();}},"plain-text",m.body||"")},{text:"Recall",style:"destructive",onPress:async()=>{await recallMessage(m.id);await load();}},{text:"Cancel",style:"cancel"}]);}
  return <SafeAreaView style={styles.screen}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}>
    <View style={styles.header}><TouchableOpacity onPress={()=>router.back()}><Text style={styles.back}>‹</Text></TouchableOpacity><View><Text style={styles.title}>Localink Chat</Text><Text style={styles.status}>Private conversation</Text></View><View style={styles.headerActions}><Text style={styles.call}>☎</Text><Text style={styles.call}>▣</Text></View></View>
    <ScrollView contentContainerStyle={styles.messages}>{messages.map(m=>{const mine=m.sender_id===myId;return <TouchableOpacity key={m.id} onLongPress={()=>actions(m)} activeOpacity={.8} style={[styles.bubble,mine?styles.mine:styles.theirs]}><Text style={[styles.body,mine&&styles.mineText]}>{m.recalled_at?"Message recalled":m.body||`${m.kind} attachment`}</Text><Text style={[styles.time,mine&&styles.mineTime]}>{new Date(m.created_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}{m.edited_at?" · edited":""}</Text></TouchableOpacity>})}</ScrollView>
    <View style={styles.composer}><TouchableOpacity style={styles.attach}><Text style={styles.attachText}>＋</Text></TouchableOpacity><TextInput value={text} onChangeText={setText} placeholder="Message" placeholderTextColor="#7B8794" multiline style={styles.input}/><TouchableOpacity style={styles.voice}><Text>◉</Text></TouchableOpacity><TouchableOpacity onPress={send} disabled={sending||!text.trim()} style={styles.send}><Text style={styles.sendText}>➤</Text></TouchableOpacity></View>
  </KeyboardAvoidingView></SafeAreaView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#EEF3F8"},header:{backgroundColor:"#071A33",padding:14,flexDirection:"row",alignItems:"center",gap:12},back:{color:"#fff",fontSize:34},title:{color:"#fff",fontWeight:"800",fontSize:17},status:{color:"#AFC4DA",fontSize:11},headerActions:{marginLeft:"auto",flexDirection:"row",gap:18},call:{color:"#fff",fontSize:20},messages:{padding:14,gap:8},bubble:{maxWidth:"80%",borderRadius:18,paddingHorizontal:13,paddingVertical:9},mine:{alignSelf:"flex-end",backgroundColor:"#1287FF",borderBottomRightRadius:5},theirs:{alignSelf:"flex-start",backgroundColor:"#fff",borderBottomLeftRadius:5},body:{color:"#17253B",fontSize:16,lineHeight:21},mineText:{color:"#fff"},time:{color:"#7B8794",fontSize:10,marginTop:4},mineTime:{color:"#D6EAFF"},composer:{backgroundColor:"#fff",borderTopWidth:1,borderTopColor:"#E1E7EE",padding:10,flexDirection:"row",alignItems:"flex-end",gap:7},input:{flex:1,maxHeight:110,backgroundColor:"#F1F5F9",borderRadius:20,paddingHorizontal:14,paddingVertical:10,color:"#0B1830"},attach:{width:38,height:38,borderRadius:19,backgroundColor:"#EAF3FF",alignItems:"center",justifyContent:"center"},attachText:{color:"#1287FF",fontSize:25},voice:{width:38,height:38,borderRadius:19,alignItems:"center",justifyContent:"center"},send:{width:40,height:40,borderRadius:20,backgroundColor:"#1287FF",alignItems:"center",justifyContent:"center"},sendText:{color:"#fff",fontSize:18,fontWeight:"800"}});
